# Generated by Django 2.2.6 on 2019-11-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_id', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('model_number', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('starting_inventory', models.IntegerField()),
                ('supplier_id', models.IntegerField()),
                ('inventory_received', models.IntegerField(default=0)),
                ('inventory_shipped', models.IntegerField(default=0)),
                ('current_inventory', models.IntegerField(default=0)),
                ('minimum_required', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_id', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('product_id', models.IntegerField()),
                ('number_shipped', models.IntegerField()),
                ('order_date', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='purchases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_id', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('product_id', models.IntegerField()),
                ('number_received', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='suppliers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_id', models.CharField(max_length=100)),
                ('supplier_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='to_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_id', models.CharField(max_length=100)),
                ('supplier_id', models.IntegerField()),
                ('model_number', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
            ],
        ),
    ]
